const Details = {
	crypto: {
		info: `A cryptocurrency (or "crypto") is a digital currency that can be used to buy goods and services, but uses an online ledger with strong cryptography to secure online transactions.\nThe defining trait of a cryptocurrency is that they are not issued by the government agency of any country making them immune against any interference and manipulation from them.`,
		fact: `1. There are more than 4,500 cryptocurrencies in existence\n2. When the protocol for Bitcoin was set up, the limit was set at 21 million. As a result, at some point, no more bitcoins can be mined.\n3. The creator (or creators) of Bitcoin remain anonymous`,
		glossary: `1. Blockchain: Blockchain is a shared, immutable ledger that facilitates the process of recording transactions and tracking assets in a business network.\n2. NFT: NFT is an acronym for a non-fungible token that is created through blockchain technology. The non-fungible token is unique in its form and not replaceable by another duplicate unit.\n3. Bitcoin: Bitcoin is the first and most widely recognized cryptocurrency. It enables peer-to-peer exchange of value in the digital realm through the use of a decentralized protocol.`,
	},
	stock: {
		info: `A stock is a piece of paper or electronic record that represents an ownership 'share' in a company. \nCompanies need to raise money to run their business. \nTo raise capital, a company may issue shares to the public for a price, trading some ownership in exchange for money. This can be done by listing on a stock market. \nA stock market is where investors buy and sell shares.`,
		fact: `1. Ramesh Damani, Rakesh Jhunjhunwala, Radhakishan Damani, Raamdeo Agrawal, and Porinju Veliyath are the major traders/investors in India.\n2. The costliest share in the Indian stock market is MRF. It costs Rs 78,350 to buy 1 share of the MRF (as of 23-Apr-2021), and the expensive share in the world is Berkshire Hathaway 4,09,169 USD (as of 23-Apr-2021).\n3. Mr. Premchand Roychand founded the Bombay Stock Exchange (BSE) in Dalal Street in 1854, and BSE is the oldest exchange in Asia.`,
		glossary: `1. Bull: A bull is a stock market speculator who buys a holding in a stock in the expectation that in the very short-term it will rise in value whereupon they will sell the stock to make a quick profit on the transaction.\n\n2. Bear: A bear is an investor who is pessimistic about the markets and expects prices to decline in the near- to medium term. A bearish investor may take short positions in the market to profit off of declining prices.\n\n3. Crash: A stock market crash is a sudden dramatic decline of stock prices across a major cross-section of a stock market, resulting in a significant loss of paper wealth.\n\n4. A boom illustrates a period of elevated or increased growth within a business, market, industry, or economy. A boom lasts over the medium- to long-term and can turn into a bubble, ultimately leading to a bust.\n\n5.IPO : An initial public offering or stock launch is a public offering in which shares of a company are sold to institutional investors and usually also retail investors`,
	},
	bank: {
		info: `A bank is a financial institution that accepts deposits from the public and creates a demand deposit while simultaneously making loans. Lending activities can be directly performed by the bank or indirectly through capital markets.`,
		fact: `1. Allahabad Bank, the oldest joint stock bank of India.\n2. Bank of India, the first bank to open a branch outside India.\n3. Central Bank of India, the first bank that was completely owned by Indians.\n4. Punjab National Bank, the largest among all the nationalized banks after SBI.\n5. UTI Bank, the first private bank in India.`,
		glossary: `1. Saving Account: Saving accounts are a type of deposit account kept by banks that pay interest. They let a person keep some of their money in the bank for immediate use. They also earn money through interest. Having a savings account in a bank allows a person to have money available for an emergency.\n2. PPF: Public Provident Fund (PPF) scheme is a long term investment option that offers an attractive rate of interest and returns on the amount invested. The interest earned and the returns are not taxable under Income Tax.\n3. Fixed Deposit: Fixed deposit is an investment vehicle which allows investors to put their idle money into and turn it into guaranteed returns. These returns are calculated at fixed FD rates in a specific time period ranging from 7 days to up to 10 years.\n4. Loan: A loan is the lending of money by one or more individuals, organizations, or other entities to other individuals, organizations etc. The recipient (i.e., the borrower) incurs a debt and is usually liable to pay interest on that debt until it is repaid as well as to repay the principal amount borrowed.\n5. ROI: Return on Investment estimates the loss and gain generated on the amount of money invested. Return on Investment is generally expressed in the percentage to analyse an organisation’s profit or the earnings of different investments. `,
	},
	tax: {
		info: `A tax is a mandatory fee or financial charge levied by any government on an individual or an organization to collect revenue for public works providing the best facilities and infrastructure. The collected fund is then used to fund different public expenditure programs. `,
		fact: `1. For incomes up to 2,50,000 INR, the tax is nil.\n2. For income slabs between 2,50,000 to 5,00,000 INR, the income tax is 5%.\n3. For income slabs between 5,00,001 to 7,50,000 the income tax is 10%.\n4. For income slabs between 7,50,001 to 10,00,000 the income tax is 15%.\n5. For income slabs between 10,00,001 to 12,50,000 the income tax is 20%.\n6. For income slabs between 12,50,001 to 15,00,000 the income tax is 25%.\n7. For people with income above 15,00,000 per year, the income tax is 30%.`,
		glossary: `1. ITR: Income Tax Return (ITR) is a form which a person is supposed to submit to the Income Tax Department of India. It contains information about the person’s income and the taxes to be paid on it during the year. Information filed in ITR should pertain to a particular financial year, i.e. starting on 1st April and ending on 31st March of the next year.\n2. Capital Gain Tax: Capital gain can be defined as any profit that is received through the sale of a capital asset. The profit that is received falls under the income category. Therefore, a tax needs to be paid on the income that is received. The tax that is paid is called capital gains tax and it can either be long term or short term. The tax that is levied on long term and short term gains starts from 10% and 15%, respectively.\n3. GST: GST is known as the Goods and Services Tax. It is an indirect tax which has replaced many indirect taxes in India such as the excise duty, VAT, services tax, etc. The Goods and Service Tax Act was passed in the Parliament on 29th March 2017 and came into effect on 1st July 2017.`,
	},
	compounding: {
		glossary: `Compound interest (or compounding interest) is the interest on a loan or deposit calculated based on both the initial principal and the accumulated interest from previous periods.`,
		info: `“Compound interest is the eighth wonderof the world. He who understands it, earns it ... he who doesn't ... pays it.”\n--Albert Einstein${" "}`,
		fact: `A = P (1 + r/n) (nt)\n\nwhere:\nA = the future value of the investment/loan, including interest\nP = the principal investment amount (the initial deposit or loan amount)\nr = the annual interest rate (decimal)\nn = the number of times that interest is compounded per unit t\nt = the time the money is invested or borrowed for`,
	},
	miscellaneous:{
		info:`There are various Miscellaneous Investments. Some of them are listed below \n\n\n1. Gold : Gold is arguably the most popular metal among traders. People use it to hedge investments when risk aversion is high because it has somewhat of a safe haven status.In addition, its value increases whenever the US dollar declines.\n\n2. Real Estate : Real estate investing involves the purchase, ownership, management, rental and/or sale of real estate for profit. Improvement of realty property as part of a real estate investment strategy is generally considered to be a sub-specialty of real estate investing called real estate development. Real estate is an asset form with limited liquidity relative to other investments.\n\n3.Investment in Startups : Investing in startup companies is a very risky business, but it can be very rewarding if and when the investments do pay off. The majority of new companies or products simply do not make it, so the risk of losing one's entire investment is a real possibility. The ones that do make it, however, can produce very high returns on investment`,
		fact:`1.The yellow metal has been growing in value for five consecutive years. In 2020 alone, gold was up close to 30% compared to the previous year. Analysts expect that gold’s rally will continue in 2021.\n\n2.The search giant Google launched as a startup in 1997 with $1 million in seed money from FF&F.In August 2004, Google's IPO raised over $1.2 billion for the company and almost half a billion dollars for those original investors, a return of almost 1,700%,\n\n4.In India, the real estate sector is the second-highest employment generator, after the agriculture sector.\n\n5.Real estate sector in India is expected to reach US$ 1 trillion by 2030. By 2025, it will contribute 13% to country’s GDP.`,
		glossary: `1. Precious Metals: Precious metals are elements that are considered rare and chemically inert. They’re not abundant in nature, and therefore they have high economic value. Precious metals are used commonly in jewelry, industrial processes, or very often as investment vehicles. \n\n2.Startup : A startup or start-up is a company or project undertaken by an entrepreneur to seek, develop, and validate a scalable business model. \n\n3.Agent : A person authorized  by the state to conduct real estate transactions. \n\n4. Down Payment: Payment term used in the context of the purchase of expensive items ,where a portion of the total amount due is usually given in cash upfront before finalizing a transaction. `
	}
};

export default Details;
